docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Introduction: intro.md
    - Reference:
      - 'Routing': routing.md
      - 'Default Services': services.md
    - Migration:
      - 'Version 2 to Version 3': migration/v2-to-v3.md
site_name: laminas-mvc-i18n
site_description: 'Integration between laminas-mvc and laminas-i18n'
repo_url: 'https://github.com/laminas/laminas-mvc-i18n'
extra:
    project: Mvc
    project_url: 'https://docs.laminas.dev'
